[project]
name = 'digtrust_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.candidate_registration]
path = 'contracts/candidate_registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.community_governance]
path = 'contracts/community_governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.data_marketplace]
path = 'contracts/data_marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.decentralized_identity]
path = 'contracts/decentralized_identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.funding]
path = 'contracts/funding.clar'
clarity_version = 2
epoch = 2.5

[contracts.multi_send_with_cross_chain_support]
path = 'contracts/multi_send_with_cross_chain_support.clar'
clarity_version = 2
epoch = 2.5

[contracts.privacy]
path = 'contracts/privacy.clar'
clarity_version = 2
epoch = 2.5

[contracts.reputation_token]
path = 'contracts/reputation_token.clar'
clarity_version = 2
epoch = 2.5

[contracts.research]
path = 'contracts/research.clar'
clarity_version = 2
epoch = 2.5

[contracts.storage_with_value_history]
path = 'contracts/storage_with_value_history.clar'
clarity_version = 2
epoch = 2.5

[contracts.tokenized_data_transaction]
path = 'contracts/tokenized_data_transaction.clar'
clarity_version = 2
epoch = 2.5

[contracts.two_factor_withdrawal_wallet]
path = 'contracts/two_factor_withdrawal_wallet.clar'
clarity_version = 2
epoch = 2.5

[contracts.user_data_control]
path = 'contracts/user_data_control.clar'
clarity_version = 2
epoch = 2.5

[contracts.user_identity]
path = 'contracts/user_identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.user_profiles]
path = 'contracts/user_profiles.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
